export ZSH="$HOME/.oh-my-zsh"

# Tema
ZSH_THEME="agnoster"

# Plugins (Adicionei os que te vão salvar tempo)
plugins=(
    git
    fzf
    docker
    kubectl
    terraform
    aws
    poetry
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# --- ALIASES ---
alias k="kubectl"
alias t="terraform"
alias awsp='export AWS_PROFILE=$(aws configure list-profiles | fzf)' # Escolher perfil AWS com FZF
alias pa="source \$(poetry env info --path)/bin/activate"            # Ativar ambiente Poetry rápido
alias zshconfig="nano ~/.zshrc"
alias reload="source ~/.zshrc"

# --- PATHS (Organizados e sem duplicados) ---
typeset -U path # Impede que o PATH tenha entradas duplicadas
path=(
    $HOME/.local/bin
    /usr/local/go/bin
    /opt/nvim-linux-x86_64/bin
    $path
)
export PATH

# --- FIXES ---
# Garante que o VirtualEnv do Python aparece no tema Agnoster
export VIRTUAL_ENV_DISABLE_PROMPT=0

# Ativação automática do Poetry se entrares numa pasta com pyproject.toml
function activate_poetry_shell {
  if [[ -f pyproject.toml && -z "$VIRTUAL_ENV" ]]; then
    source $(poetry env info --path)/bin/activate 2>/dev/null
  fi
}
autoload -U add-zsh-hook
add-zsh-hook chpwd activate_poetry_shell



# install plugins
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
